SELECT r.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS,
    ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW AS r
JOIN REST_INFO AS i ON r.REST_ID = i.REST_ID
GROUP BY r.REST_ID
HAVING i.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, i.FAVORITES DESC;