SELECT YEAR(SALES_DATE) AS 'YEAR',
    MONTH(SALES_DATE) AS 'MONTH',
    GENDER, COUNT(DISTINCT o.USER_ID) AS 'USERS'
FROM USER_INFO AS u
    JOIN ONLINE_SALE AS o ON u.USER_ID = o.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER