SELECT CATEGORY,
    SUM(s.SALES) AS TOTAL_SALES
FROM BOOK AS b
JOIN BOOK_SALES AS s
ON b.BOOK_ID = s.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY